name: com.example.my_flutter_app
description: A Flutter application demonstrating state management using the Cubit pattern. The app includes two main screens: a home screen displaying a list of items and a details screen showing details of a selected item.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true